Repository salemlf/hakubun, pull requests merged in 2024-05, with the labels that each got.

#198 User Note Info
  src/components/Modal/Modal.tsx
  src/components/UserNote/EditNoteModal.tsx
Labels: enhancement

#200 Review and Lesson Summary Pages Stuck Bug
  src/components/AssignmentQueueCards/AssignmentQueueCards.tsx
Labels: bug

#211 Log Out Confirmation Dialog
  src/pages/Settings.tsx
Labels: enhancement

#212 Bug Fix: Alternative Meaning Not Accepted In Review and Lesson Sessions
  src/components/AssignmentQueueCards/AssignmentQueueCards.tsx
  src/services/AssignmentQueueService/AssignmentQueueService.ts
  src/stores/useAssignmentQueueStore/useAssignmentQueueStore.test.ts
  src/stores/useAssignmentQueueStore/useAssignmentQueueStore.ts
Labels: bug

#214 App Web Build and Android/iOS Debugging and Inspecting Instructions
  README.md
  resources/debugging-screenshots/chrome-remote-targets.png
  resources/debugging-screenshots/chrome-web-inspector.png
  resources/debugging-screenshots/safari-inspecting-ios-device.png
  resources/debugging-screenshots/safari-select-ios-simulator.png
Labels: documentation

#220 Fix for #204: doesn't honor batch size if cards are less than batch size
  src/components/BasicAssignmentSettings/BasicAssignmentSettings.tsx
Labels: bug

#235 License and Testing Info
  README.md
  license.md
Labels: documentation

#251 Bump App Version Branch Creation Reorder
  .github/workflows/bump-app-version.yml
Labels: cicd

#257 Refactor bump app build number and update version name
  .github/workflows/bump-app-version.yml
  fastlane/Fastfile
Labels: cicd

#260 Generate Changelog on App Version Update
  .github/config/changelog-config.json
  .github/workflows/bump-app-version.yml
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: cicd

#261 Revert "Bump App to Version 1.2.0-beta"
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: ignore in changelog

#262 Prevent Alt Meaning Modal Close on Outside Click, Increase "Add" Button Size
  src/components/Button/Button.tsx
  src/components/Label/Label.tsx
  src/components/LessonsButton/LessonsButton.tsx
  src/components/Modal/Modal.tsx
  src/components/ReviewsButton/ReviewsButton.tsx
  src/components/SubjectMeanings/AddAltUserMeaningButton.tsx
  src/components/UserNote/EditNoteModal.tsx
  src/styles/BaseStyledComponents.tsx
  src/theme/globals.scss
  src/theme/variables.css
Labels: bug, styling

#263 Formatted Fastlane Files
  .github/workflows/build-android-app-bundle.yml
  .github/workflows/build-dev-android-apk.yml
  .rubocop.yml
  .vscode/extensions.json
  Gemfile
  Gemfile.lock
  README.md
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Gymfile
  fastlane/Matchfile
  fastlane/README.md
Labels: ignore in changelog

#264 Release Creation Workflow - Deploying iOS and Android Beta Apps
  .github/workflows/create-prerelease.yml
  fastlane/Fastfile
  fastlane/README.md
Labels: cicd

#265 Updated Capacitor to v6
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/variables.gradle
  ios/App/Podfile.lock
  package-lock.json
  package.json
  public/mockServiceWorker.js
Labels: dependencies

#266 Button Color Contrast Improvements
  src/components/BackButton/BackButton.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/QueueHeader/QueueHeader.tsx
  src/pages/Settings.tsx
Labels: styling

#237 Account for iOS Notch/Safe Areas
  capacitor.config.ts
  src/components/BottomSheet/BottomSheet.tsx
  src/components/RootContainer/RootContainer.tsx
  src/pages/Subjects.tsx
  src/theme/globals.scss
Labels: bug, iOS

#268 Changelog Compares Most Recent Updates
  .github/config/changelog-config.json
  .github/workflows/bump-app-version.yml
Labels: cicd

#270 Changelog Category Refinement
  .github/config/changelog-config.json
Labels: cicd

#271 App Version Updated to 2.0.0-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/50.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#273 Deploy Android Beta App Workflow Fixes
  .github/workflows/create-prerelease.yml
  .github/workflows/deploy-beta-android.yml
Labels: cicd

#274 Deploy Android Beta App - Android Specify Package Name
  .github/workflows/create-prerelease.yml
  .github/workflows/deploy-beta-android.yml
  fastlane/Fastfile
Labels: cicd

#275 Deploy iOS Workflow - Remove Username
  fastlane/Fastfile
Labels: iOS, cicd

#276 Truncate Changelog
  .github/config/changelog-config.json
  fastlane/metadata/android/en-US/changelogs/50.txt
Labels: documentation

#277 Removing Prerelease from iOS Version
  .github/workflows/bump-app-version.yml
  ios/App/App/Info.plist
Labels: iOS, cicd

#278 Truncate Changelog, Link to Full Release Notes
  .github/config/changelog-config.json
  .github/workflows/bump-app-version.yml
  fastlane/metadata/android/en-US/changelogs/50.txt
Labels: documentation, cicd

#279 Mismatching Radical Image in Reviews and Lessons
  src/components/AssignmentQueueCards/AssignmentCharAndType.tsx
  src/components/ImageFallback/ImageFallback.tsx
  src/components/SubjectChars/SubjectChars.tsx
Labels: bug

#280 Render Italics in Meaning and Reading Explanations
  src/components/TxtWithSubjTags/TxtWithSubjTags.tsx
  src/components/TxtWithSubjTags/constants.ts
Labels: bug

#281 Lighten Background Color for Search Clear Button
  src/pages/Search.tsx
Labels: styling

#282 Consistent Reviews and Lessons Button Styles
  src/components/ReviewsButton/ReviewsButton.tsx
Labels: styling

#283 Defaulting to In Review When Deploying Apps
  fastlane/Fastfile
Labels: cicd

#285 Contributing Info
  .github/CONTRIBUTING
  README.md
Labels: documentation

#288 App Version Updated to 2.0.1-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/51.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#289 iOS Upload to Testflight - Invalid Parameter
  fastlane/Fastfile
Labels: cicd

#292 Indicating Primary Kanji Reading(s)
  src/components/HelpSpan/HelpSpan.tsx
  src/components/ReadingsForKanji/ReadingsForKanji.tsx
Labels: enhancement

#293 Release Notes Generation Fix for Create Prerelease Workflow
  .github/workflows/create-prerelease.yml
Labels: cicd

#294 App Version Updated to 2.1.0-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/52.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#295 Displays Error Info on Review and Lesson Summary Pages
  src/components/AssignmentQueueCards/AssignmentQueueCards.test.tsx
  src/hooks/assignments/useSubmittedQueueUpdate.ts
  src/pages/LessonQuiz.tsx
  src/pages/LessonSummary.tsx
  src/pages/ReviewSession.test.tsx
  src/pages/ReviewSession.tsx
  src/pages/ReviewSummary.tsx
  src/stores/useAssignmentSubmitStore/useAssignmentSubmitStore.ts
  src/types/AssignmentQueueTypes.ts
Labels: enhancement

#297 Automatically Deploy iOS Beta to External Testers
  fastlane/Fastfile
Labels: iOS, cicd

#298 Link PR Author in Release Notes
  .github/config/app-release-config.json
Labels: cicd

#299 App Version Updated to 2.2.0-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/53.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#300 Lessons Displaying Error on Summary Page
  src/pages/LessonQuiz.tsx
Labels: bug

#301 Subject Details SRS Level and Review Availability Font Size
  src/components/SubjectSummary/AssignmentSrs.tsx
Labels: styling

#302 App Version Updated to 2.2.1-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/54.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#304 Typing Review Update Response
  src/pages/ReviewSession.tsx
Labels: refactor

#305 Typing Lesson Start Response
  src/pages/LessonQuiz.tsx
Labels: refactor

#308 Retry Delay Configuration for Rate Limiting
  src/App.tsx
  src/services/ApiQueryService/ApiQueryService.tsx
Labels: bug

#309 Show Context Sentence Translation Button Size
  src/components/ContextSentences/ContextSentences.tsx
Labels: styling

#310 App Version Updated to 2.2.2-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/55.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#311 Setting to Proceed to Next Queue Item After Correct Answer
  src/components/AssignmentQueueCards/AssignmentQueueCards.hooks.ts
  src/components/AssignmentQueueCards/AssignmentQueueCards.test.tsx
  src/components/LessonUserSettings/LessonUserSettings.tsx
  src/components/ReviewUserSettings/ReviewUserSettings.tsx
  src/components/Switch/Switch.service.ts
  src/stores/useUserSettingsStore/useUserSettingsStore.facade.ts
  src/stores/useUserSettingsStore/useUserSettingsStore.ts
  src/testing/mocks/api-responses/review-responses.ts
  src/testing/mocks/data-generators/subjectGenerator.ts
Labels: enhancement

#312 Default Button Color Styling Fix
  src/components/Button/Button.tsx
  src/components/SubjectMeanings/AddAltUserMeaningButton.tsx
  src/pages/ErrorOccurred.tsx
  src/theme/globals.scss
  src/theme/variables.css
Labels: styling

#313 App Version Updated to 2.3.0-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/56.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#316 Show/Hide Token Button Icon Color
  src/images/crossed-out-eye.svg
  src/images/open-eye.svg
  src/pages/TokenInput.tsx
Labels: styling

#317 App Version Updated to 2.3.0-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/56.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#318 Account for Multiple Lines in Prerelease Creation Command
  .github/workflows/create-prerelease.yml
Labels: cicd

#319 Cat-ing Changelog Output into GitHub Release Notes Option
  .github/workflows/create-prerelease.yml
Labels: cicd

#320 Widths for Switch Component Increased
  src/components/Switch/Switch.service.ts
Labels: styling

#321 Placeholders No Longer Displaying on Top of Search Box
  src/pages/Search.tsx
Labels: styling, animation

#322 App Version Updated to 2.3.1-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/57.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version
