Repository salemlf/hakubun, pull requests merged in 2024-04, with the labels that each got.

#173 User Error Reporting
  .github/workflows/build-android-app-bundle.yml
  .github/workflows/build-dev-android-apk.yml
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  ios/App/Podfile
  ios/App/Podfile.lock
  package-lock.json
  package.json
  src/App.tsx
  src/api/OctokitApi.ts
  src/components/ErrReportModal/ErrReportModal.test.tsx
  src/components/ErrReportModal/ErrReportModal.tsx
  src/components/ErrReportModal/index.ts
  src/components/Popover/Popover.tsx
  src/components/Switch/Switch.tsx
  src/hooks/octokit/useCreateIssue.ts
  src/images/paper-airplane.svg
  src/pages/ErrorOccurred.tsx
  src/services/ProfanityFilterService/ProfanityFilterService.test.ts
  src/services/ProfanityFilterService/ProfanityFilterService.ts
  src/testing/endpoints.ts
  src/types/Octokit.ts
Labels: bug, enhancement

#179 User Feedback
  package-lock.json
  package.json
  src/components/Accordion/Accordion.tsx
  src/components/AlertModal/AlertModal.tsx
  src/components/AssignmentSelector/AssignmentSelector.tsx
  src/components/AssignmentTypeSelector/AssignmentTypeSelector.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Button/Button.tsx
  src/components/Collapsible/Collapsible.tsx
  src/components/ColorThemeSwitch/ColorThemeSwitch.tsx
  src/components/ErrReportModal/index.ts
  src/components/HelpSpan/HelpSpan.tsx
  src/components/LessonsButton/LessonsButton.tsx
  src/components/Modal/Modal.tsx
  src/components/ReviewsButton/ReviewsButton.tsx
  src/components/Selector/Selector.tsx
  src/components/SrsStages/SrsStages.tsx
  src/components/SubjectButton/PopoverSubjButton.tsx
  src/components/SubjectMeanings/AddAltUserMeaningButton.tsx
  src/components/SwipeableTabs/SwipeableTabs.tsx
  src/components/SwipeableTabs/TabList.tsx
  src/components/Switch/Switch.tsx
  src/components/UserFeedbackModal/ErrReportModal.test.tsx
  src/components/UserFeedbackModal/ErrReportModal.tsx
  src/components/UserFeedbackModal/IssueLink.tsx
  src/components/UserFeedbackModal/UserFeedbackModal.hooks.tsx
  src/components/UserFeedbackModal/UserFeedbackModal.tsx
  src/components/UserFeedbackModal/index.ts
  src/hooks/useModalContainer.ts
  src/pages/ErrorOccurred.tsx
  src/pages/Search.tsx
  src/pages/Settings.tsx
  src/pages/Subjects.tsx
  src/pages/TokenInput.tsx
  src/styles/BaseStyledComponents.tsx
  src/styles/SubjectButtonsStyled.tsx
  src/theme/globals.scss
Labels: bug, enhancement

#182 Updated Android Screen Resize Method
  android/app/src/main/AndroidManifest.xml
Labels: bug

#187 SRS Button and Feedback Modal Bug Fixes
  src/components/HelpSpan/HelpSpan.tsx
  src/components/Label/Label.tsx
  src/components/SrsStages/SrsButton.tsx
  src/components/SrsStages/SrsStages.tsx
  src/components/UserFeedbackModal/UserFeedbackModal.tsx
Labels: bug

#186 Add filter by last update date
  src/components/AdvancedAssignmentFilters/AdvancedAssignmentFilters.tsx
  src/components/AdvancedAssignmentSettings/AdvancedAssignmentSettings.tsx
  src/components/AssignmentSelector/AssignmentSelector.tsx
  src/components/AssignmentSettings/AssignmentSettings.tsx
  src/components/LastUpdateOption/LastUpdateOption.constants.ts
  src/components/LastUpdateOption/LastUpdateOption.tsx
  src/components/LastUpdateOption/LastUpdateOption.types.ts
  src/services/SubjectAndAssignmentService/SubjectAndAssignmentService.ts
Labels: enhancement

#192 Assignment Settings Refactor
  __mocks__/zustand.ts
  src/components/AdvancedAssignmentFilters/AdvancedAssignmentFilters.tsx
  src/components/AdvancedAssignmentSettings/AdvancedAssignmentSettings.tsx
  src/components/AssignmentSelector/AssignmentSelector.tsx
  src/components/AssignmentSettings/AssignmentSettings.test.tsx
  src/components/AssignmentSettings/AssignmentSettings.tsx
  src/components/BackToBackOption/BackToBackOption.tsx
  src/components/BasicAssignmentSettings/BasicAssignmentSettings.tsx
  src/components/BatchSizeOption/BatchSizeOption.tsx
  src/components/LastUpdateOption/LastUpdateOption.tsx
  src/components/LastUpdateOption/index.ts
  src/components/LessonsButton/LessonsButton.test.tsx
  src/components/ReviewUserSettings/ReviewUserSettings.tsx
  src/components/SortOrderOption/SortOrderOption.tsx
  src/contexts/AssignmentSettingsContext.tsx
  src/pages/LessonSettings.test.tsx
  src/pages/LessonSettings.tsx
  src/pages/ReviewSettings.test.tsx
  src/pages/ReviewSettings.tsx
  src/stores/useAssignmentSettingsCtxStore/useAssignmentSettingsCtxStore.ts
  src/testing/test-utils.tsx
Labels: refactor

#194 Accidental Clicks Below Selector Overlay Bug Fix
  src/components/Selector/Selector.tsx
Labels: bug
