Repository salemlf/hakubun, pull requests merged in 2024-06, with the labels that each got.

#325 README Style Improvements, Link iOS App
  README.md
  resources/app-store-icon.svg
  resources/play-store-icon.svg
Labels: documentation, styling

#326 README Linking Important Sections
  .github/CONTRIBUTING.md
  README.md
  resources/app-store-icon.svg
  resources/play-store-icon.svg
  resources/play-store.svg
  resources/testflight.svg
Labels: documentation, styling

#328 README Links Fix
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#329 Reduce README Screenshot Sizes
  README.md
Labels: documentation

#333 Swipeable Tabs
  package-lock.json
  package.json
  src/components/AssignmentQueueItemBottomSheet/AssignmentQueueItemBottomSheet.tsx
  src/components/AssignmentSettings/AssignmentSettings.tsx
  src/components/KanjiDetailTabs/KanjiDetailTabs.tsx
  src/components/LessonCards/LessonCards.tsx
  src/components/RadicalDetailTabs/RadicalDetailTabs.tsx
  src/components/ReviewForecast/ReviewForecast.tsx
  src/components/SwipeableTabs/SwipeableTabs.tsx
  src/components/SwipeableTabs/index.ts
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/Tabs.types.ts
  src/components/Tabs/TabsList.tsx
  src/components/Tabs/constants.ts
  src/components/Tabs/index.ts
  src/components/VocabDetailTabs/VocabDetailTabs.tsx
  src/testing/setup.ts
  src/utils.ts
Labels: bug, refactor

#335 react-snap-carousel Testing Mock Fix
  src/testing/setup.ts
Labels: tests

#336 Cannot Delete Existing Meaning or Reading Note
  src/services/MiscService/MiscService.ts
Labels: bug

#337 App Version Updated to 2.3.2-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/58.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#340 Content Cut Off at Bottom of Subject Info Tab Content
  src/components/Tabs/Tabs.tsx
Labels: bug

#341 Select Subject Info Tab Based on Assignment Queue Card Type
  src/components/Tabs/Tabs.tsx
Labels: bug

#342 App Version Updated to 2.3.3-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/59.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#343 Decrease Height of Help Span Punctation
  src/components/HelpSpan/HelpSpan.tsx
Labels: styling

#344 Vocab Pitch Accent Info
  README.md
  src/api/ApiConfig.ts
  src/api/JotobaApi.ts
  src/components/GeneralUserSettings/GeneralUserSettings.tsx
  src/components/PitchIllustration/PitchIllustration.tsx
  src/components/PitchIllustration/index.ts
  src/components/VocabReadings/VocabReadings.tsx
  src/hooks/jotoba/useSearchWord.ts
  src/pages/Settings.tsx
  src/stores/useUserSettingsStore/useUserSettingsStore.facade.ts
  src/stores/useUserSettingsStore/useUserSettingsStore.ts
  src/types/Jotoba.ts
Labels: enhancement

#345 App Version Updated to 2.4.0-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/60.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#349 Review More Button
  src/components/AssignmentSettings/AssignmentSettings.tsx
  src/pages/ReviewSettings.tsx
  src/pages/ReviewSummary.tsx
Labels: enhancement

#350 App Version Updated to 2.5.0-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/61.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#352 App Version Updated to 2.5.1-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/62.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#353 Pitch Accent Nodes Misaligned
  src/components/PitchIllustration/PitchIllustration.tsx
Labels: bug

#354 Search Input Not Allowing Spaces
  src/pages/Search.tsx
Labels: bug

#355 App Version Updated to 2.5.2-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/63.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#360 First Tab Wasn't Selected for Vocab Lessons
  src/components/LessonCards/LessonCards.tsx
  src/components/VocabDetailTabs/VocabDetailTabs.tsx
Labels: bug

#362 Reduce Card Swipe and Appearance Animation Transition Times
  src/components/AssignmentQueueCards/AssignmentQueueCard.tsx
Labels: enhancement, animation

#363 App Version Updated to 2.5.3-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/64.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#365 Previous Card Ghosting on Retry and Advance Swipe
  src/components/AssignmentQueueCards/AssignmentQueueCard.tsx
Labels: bug

#366 Slightly Increase Card Swipe Sensitivity
  src/components/AssignmentQueueCards/AssignmentQueueCard.tsx
Labels: animation

#367 App Version Updated to 2.5.4-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/65.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#368 Partial Page Scroll Restoration Support
  package-lock.json
  package.json
  src/pages/Home.tsx
  src/pages/Search.tsx
  src/pages/SubjectDetails.tsx
  src/pages/Subjects.tsx
Labels: enhancement

#369 Tab List Y-Axis Overflow
  src/components/Tabs/TabsList.tsx
Labels: bug, styling

#370 Assignment Settings Loading and Error Page State and "Do More Reviews" Button Fix
  src/components/AssignmentSettings/AssignmentSettings.tsx
Labels: bug

#371 App Version Updated to 2.6.0-beta
  android/app/build.gradle
  fastlane/metadata/android/en-US/changelogs/66.txt
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  package-lock.json
  package.json
Labels: bump version

#380 Reduce wrapping up animation time
  src/pages/ReviewSession.tsx
Labels: animation

#379 "End Session/Quiz" Dialog Confirmation Appearing on Summary Pages
  src/components/LeaveSessionPrompt/LeaveSessionPrompt.tsx
Labels: bug
